<div class="c-Content__line">
    <div class="Grilla">
        <div class="Grilla__xs--12 Grilla__sm--4 Grilla__md--4 Grilla__lg--3 c-Panel">
            <div class="c-Panel__body">
                <h3 class="c-Panel__title">1000</h3>
                <p class="c-Panel__content">Trafico este més</p>
                <div class="c-Progress">
                    <div class="c-Progress__bar"></div>
                </div>
            </div>
        </div>
        <div class="Grilla__xs--12 Grilla__sm--4 Grilla__md--4 Grilla__lg--3 c-Panel">
            <div class="c-Panel__body">
                <h3 class="c-Panel__title">1000</h3>
                <p class="c-Panel__content">Trafico este més</p>
                <div class="c-Progress">
                    <div class="c-Progress__bar"></div>
                </div>
            </div>
        </div>
        <div class="Grilla__xs--12 Grilla__sm--4 Grilla__md--4 Grilla__lg--3 c-Panel">
            <div class="c-Panel__body">
                <h3 class="c-Panel__title">1000</h3>
                <p class="c-Panel__content">Trafico este més</p>
                <div class="c-Progress">
                    <div class="c-Progress__bar"></div>
                </div>
            </div>
        </div>
        <div class="Grilla__xs--12 Grilla__sm--4 Grilla__md--4 Grilla__lg--3 c-Panel">
            <div class="c-Panel__body">
                <h3 class="c-Panel__title">1000</h3>
                <p class="c-Panel__content">Trafico este més</p>
                <div class="c-Progress">
                    <div class="c-Progress__bar"></div>
                </div>
            </div>
        </div>
    </div>
</div>