// ACCIONES PARA AUTH
export const LOGIN_USER = 'LOGIN_USER';
export const BAD_USER = 'BAD_USER';
export const LOGOUT = 'LOGOUT';

//NOTIFICACIONES
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';


//PRODUCTOS
export const SET_PRODUCTOS = 'SET_PRODUCTOS';
export const ADD_PRODUCTO = 'ADD_PRODUCTO';
export const FETCH_NEW_PRODUCT = 'FETCH_NEW_PRODUCT';
export const CLOSE_MODAL_PRODUCTO_NUEVO = 'CLOSE_MODAL_PRODUCTO_NUEVO';
export const OPEN_MODAL_PRODUCTO_NUEVO = 'OPEN_MODAL_PRODUCTO_NUEVO';
export const OPEN_MODAL_ADD_PRODUCTO = 'OPEN_MODAL_ADD_PRODUCTO';
export const CLOSE_MODAL_ADD_PRODUCTO = 'CLOSE_MODAL_ADD_PRODUCTO';
export const CLOSE_MODAL_DEL_PRODUCTO = 'CLOSE_MODAL_DEL_PRODUCTO';
export const OPEN_MODAL_DEL_PRODUCTO = 'OPEN_MODAL_DEL_PRODUCTO';
export const SET_ELIMINAR_PRODUCTO = 'SET_ELIMINAR_PRODUCTO';
export const OPEN_MODAL_EDITAR_PRODUCTO = 'OPEN_MODAL_EDITAR_PRODUCTO';
export const CLOSE_MODAL_EDITAR_PRODUCTO = 'CLOSE_MODAL_EDITAR_PRODUCTO';
export const SET_UPDATE_PRODUCTO = 'SET_UPDATE_PRODUCTO';

//CLIENTES
export const SET_CLIENTES = 'SET_CLIENTES';
export const ADD_CLIENTE = 'ADD_CLIENTE';
export const FETCH_NEW_CLIENT = 'FETCH_NEW_CLIENT';
export const FETCH_UPDATE_CLIENT = 'FETCH_UPDATE_CLIENT';
export const OPEN_MODAL_CLIENTE_NUEVO = 'OPEN_MODAL_CLIENTE_NUEVO';
export const CLOSE_MODAL_CLIENTE_NUEVO = 'CLOSE_MODAL_CLIENTE_NUEVO ';
export const CLOSE_MODAL_ADD_CLIENTE = 'CLOSE_MODAL_ADD_CLIENTE ';
export const OPEN_MODAL_ADD_CLIENTE = 'OPEN_MODAL_ADD_CLIENTE ';
export const OPEN_MODAL_DEL_CLIENTE = 'OPEN_MODAL_DEL_CLIENTE ';
export const CLOSE_MODAL_DEL_CLIENTE = 'CLOSE_MODAL_DEL_CLIENTE ';
export const SET_ELIMINAR_CLIENTE = 'SET_ELIMINAR_CLIENTE ';
export const OPEN_MODAL_UPDATE_CLIENT = 'OPEN_MODAL_UPDATE_CLIENT ';
export const CLOSE_MODAL_UPDATE_CLIENT = 'CLOSE_MODAL_UPDATE_CLIENT ';
export const SET_UPDATE_CLIENT = 'SET_UPDATE_CLIENT ';

//FACTURAS
export const SET_FACTURAS = 'SET_FACTURAS';
export const OPEN_MODAL_FACTURA_NUEVA = 'OPEN_MODAL_FACTURA_NUEVA';
export const CLOSE_MODAL_FACTURA_NUEVA = 'CLOSE_MODAL_FACTURA_NUEVA';
export const ADD_PRODUCTO_IN_FACTURA = 'ADD_PRODUCTO_IN_FACTURA';
export const DELETE_PRODUCTO_OUT_FACTURA = 'DELETE_PRODUCTO_OUT_FACTURA';
export const ADD_CLIENTE_IN_FACTURA = 'ADD_CLIENTE_IN_FACTURA';
export const ADD_PAGO_IN_FACTURA = 'ADD_PAGO_IN_FACTURA';
export const ADD_ESTADO_PAGO_IN_FACTURA = 'ADD_ESTADO_PAGO_IN_FACTURA';
export const CLEAR_NEW_FACTURA = 'CLEAR_NEW_FACTURA';
export const ADD_NEW_FACTURA = 'ADD_NEW_FACTURA';
export const OPEN_MODAL_DEL_FACTURA = 'OPEN_MODAL_DEL_FACTURA';
export const CLOSE_MODAL_DEL_FACTURA = 'CLOSE_MODAL_DEL_FACTURA';
export const SET_ELIMINAR_FACTURA = 'SET_ELIMINAR_FACTURA';
export const OPEN_MODAL_UPDATE_FACTURA = 'OPEN_MODAL_UPDATE_FACTURA';
export const CLOSE_MODAL_UPDATE_FACTURA = 'CLOSE_MODAL_UPDATE_FACTURA';
export const ADD_PRODUCTOS_IN_FACTURA = 'ADD_PRODUCTOS_IN_FACTURA';

//METODOS DE PAGO
export const SET_METODOS_PAGOS = 'SET_METODOS_PAGOS';

// ESTADOS DE PAGO
export const SET_ESTADOS_PAGOS = 'SET_ESTADOS_PAGOS';

//EMPRESA DATOS
export const SET_EMPRESA_DATOS = 'SET_EMPRESA_DATOS';
export const SET_MODIFICAR_EMPRESA = 'SET_MODIFICAR_EMPRESA';