<div class="l-Widget">
    <header class="l-Widget__header">
        <h3 class="l-Widget__title">Crear raza animal</h3>
    </header>
    <section class="l-Widget__body">
        <div class="l-Widget__container">
            <form action="" method="POST" class="Form">
                <div class="Form__group">
                    <label>Nombre Raza</label>
                    <input type="text" name="nombre" class="Form__control" placeholder="Nombre de la raza">
                </div>
                <div class="Form__group">
                    <button class="Boton Boton--raised-cyan">
                        Crear nueva raza
                    </button>
                    <a href="<?= base_url('codeunic/razas/tipo/' . $this->_tipoAnimal) ?>" class="Boton">
                        Atras
                    </a>
                </div>
            </form>
        </div>
    </section>
</div>