<div class="error-box">
    <div class="error-body text-center">
        <h1><?= $this->code; ?></h1>
        <h3 class="text-uppercase"><?= $this->mensaje; ?></h3>
        <p class="text-muted m-t-30 m-b-30"></p>
        <a href="<?= base_url("index/"); ?>" class="btn btn-info btn-rounded waves-effect waves-light m-b-40">Back to home</a></div>
    <footer class="footer text-center"><?= $this->config->obtener("copyright"); ?></footer>
</div>